// account
export const ACCOUNT_REQUEST_ERROR = '@@account/ACCOUNT_REQUEST_ERROR'

export const LOGIN_REQUEST = '@@account/LOGIN_REQUEST'
export const LOGIN_SUCCESS = '@@account/LOGIN_SUCCESS'

export const GET_PROFILE_REQUEST = '@@account/GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = '@@account/GET_PROFILE_SUCCESS'

export const ACTIVATE_REQUEST = '@@account/ACTIVATE_REQUEST'
export const ACTIVATE_SUCCESS = '@@account/ACTIVATE_SUCCESS'

export const LOGOUT_REQUEST = '@@account/LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = '@@account/LOGOUT_SUCCESS'

export const REGISTER_REQUEST = '@@account/REGISTER_REQUEST'
export const REGISTER_SUCCESS = '@@account/REGISTER_SUCCESS'

export const UPDATE_EMAIL_REQUEST = '@@account/UPDATE_EMAIL_REQUEST'
export const UPDATE_EMAIL_SUCCESS = '@@account/UPDATE_EMAIL_SUCCESS'

export const SEND_ACTIVATE_EMAIL_REQUEST = '@@account/SEND_ACTIVATE_EMAIL_REQUEST'
export const SEND_ACTIVATE_EMAIL_SUCCESS = '@@account/SEND_ACTIVATE_EMAIL_SUCCESS'

export const VALIDATE_ACCOUNT_REQUEST = '@@account/VALIDATE_ACCOUNT_REQUEST'
export const VALIDATE_ACCOUNT_SUCCESS = '@@account/VALIDATE_ACCOUNT_SUCCESS'

// countdown
export const SET_COUNTDOWN = '@@countdown/SET_COUNTDOWN'

// topics
export const TOPIC_REQUEST_ERROR = '@@topic/TOPIC_REQUEST_ERROR'

export const CLEAR_TOPICS = '@@topics/CLEAR_TOPICS'

export const FETCH_TOPICS_REQUEST = '@@topic/FETCH_TOPICS_REQUEST'
export const FETCH_TOPICS_SUCCESS = '@@topic/FETCH_TOPICS_SUCCESS'

export const FETCH_TOPICS_PAGES_REQUEST = '@@topic/FETCH_TOPICS_PAGES_REQUEST'
export const FETCH_TOPICS_PAGES_SUCCESS = '@@topic/FETCH_TOPICS_PAGES_SUCCESS'

export const FETCH_TOPICS_CATEGORYS_REQUEST = '@@topic/FETCH_TOPICS_CATEGORYS_REQUEST'
export const FETCH_TOPICS_CATEGORYS_SUCCESS = '@@topic/FETCH_TOPICS_CATEGORYS_SUCCESS'

export const CREATE_NEW_TOPIC_REQUEST = '@@topic/CREATE_NEW_TOPIC_REQUEST'
export const CREATE_NEW_TOPIC_SUCCESS = '@@topic/CREATE_NEW_TOPIC_SUCCESS'

export const FETCH_TOPIC_DEDAIL_REQUEST = '@@topic/FETCH_TOPIC_DETAIL_REQUEST'
export const FETCH_TOPIC_DEDAIL_SUCCESS = '@@topic/FETCH_TOPIC_DETAIL_SUCCESS'

export const REPLY_TOPIC_REQUEST = '@@topic/REPLY_TOPIC_REQUEST'
export const REPLY_TOPIC_SUCCESS = '@@topic/REPLY_TOPIC_SUCCESS'

export const LIKE_TOPIC_REQUEST = '@@topic/LIKE_TOPIC_REQUEST'
export const LIKE_TOPIC_SUCCESS = '@@topic/LIKE_TOPIC_SUCCESS'
